import scrapy

class ReviewItem(scrapy.Item):
    valuation = scrapy.Field()
    title = scrapy.Field()
    description = scrapy.Field()
    authors = scrapy.Field()
    editors = scrapy.Field()
    date = scrapy.Field()
    comments = scrapy.Field()
    visual_overview = scrapy.Field()
    platforms = scrapy.Field()
    developers = scrapy.Field()
    publishers = scrapy.Field()
    genres = scrapy.Field()
    verdict = scrapy.Field()
    text = scrapy.Field()
    screenshots = scrapy.Field()
    passed_on = scrapy.Field()
    theme = scrapy.Field()
    duration = scrapy.Field()
    score = scrapy.Field()
    laugh = scrapy.Field()
    joy = scrapy.Field()
    disgust = scrapy.Field()
    surprise = scrapy.Field()
    anger = scrapy.Field()
    bitterness = scrapy.Field()
    interest = scrapy.Field()
    poker = scrapy.Field()
    url = scrapy.Field()

class NewsItem(scrapy.Item):
    valuation = scrapy.Field()
    title = scrapy.Field()
    authors = scrapy.Field()
    date = scrapy.Field()
    comments = scrapy.Field()
    visual_overview = scrapy.Field()
    platforms = scrapy.Field()
    categories = scrapy.Field()
    tags = scrapy.Field()
    website = scrapy.Field()
    text = scrapy.Field()
    laugh = scrapy.Field()
    joy = scrapy.Field()
    disgust = scrapy.Field()
    surprise = scrapy.Field()
    anger = scrapy.Field()
    bitterness = scrapy.Field()
    interest = scrapy.Field()
    poker = scrapy.Field()